wandb_version: 1

corr_type:
  desc: null
  value: gauss
perc_noise:
  desc: null
  value: 0.05
valid:
  desc: null
  value: false
verbose:
  desc: null
  value: false
wandb:
  desc: null
  value: le-project
