wandb_version: 1

ckpt_on:
  desc: null
  value: false
corr_type:
  desc: null
  value: sp
perc_noise:
  desc: null
  value: 0.05
valid:
  desc: null
  value: false
verbose:
  desc: null
  value: false
wandb:
  desc: null
  value: le-project
